---
title: "Report Plots"
author: "Amber Hu"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r, include=FALSE}
library(DBI)
library(ggplot2)
library(circlize)
library(magrittr)
library(dplyr)
library(grid)

dcon <- dbConnect(RSQLite::SQLite(), 
                  dbname = "chicago_crimes_db.sqlite")

```


```{sql, connection=dcon, output.var='mydf1', include=FALSE}
SELECT Year, LocationDescription AS ld, count(*) AS n
FROM chicago_crimes
WHERE ld IN top8ld AND Year < 2022
GROUP BY Year, ld;
```


```{sql, connection=dcon, output.var='mydf2', include=FALSE}
SELECT substring(Date, 1, 2) AS Month, LocationDescription AS ld, count(*) AS n
FROM chicago_crimes
WHERE ld IN top8ld AND Year < 2022
GROUP BY Month, ld;
```


```{sql, connection=dcon, output.var='mydf3', include=FALSE}
SELECT *
FROM time_ld
```


```{sql, connection=dcon, output.var='mydf4', include=FALSE}
SELECT Year, PrimaryType AS pt, count(*) AS n
FROM chicago_crimes
WHERE pt IN top8pt AND Year < 2022
GROUP BY Year, pt;
```


```{sql, connection=dcon, output.var='mydf5', include=FALSE}
SELECT substring(Date, 1, 2) AS Month, PrimaryType AS pt, count(*) AS n
FROM chicago_crimes
WHERE pt IN top8pt AND Year < 2022
GROUP BY Month, pt;
```


```{sql, connection=dcon, output.var='mydf6', include=FALSE}
SELECT *
FROM time_pt
```

```{r, include=FALSE}
#by location, year
ggplot(data = mydf1) +
  aes(x = Year, y = n, color = ld) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = 2001:2021) +
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5)) +
  labs(x = "Year", y = "Count",
       title = "Number of Reported Crimes by Year and Location Description",
       col = "Location Description") +
  scale_color_discrete(name = "",
                       labels = c('Alley', 'Apartment', 'Public parking',
                                  'Residence', 'School, public, building',
                                  'Sidewalk', 'Small retail store', 'Street')) -> yl

#by location, month
mydf2$Month <- as.numeric(mydf2$Month)
ggplot(data = mydf2) +
  aes(x = Month, y = n, color = ld) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = 1:12) +
  labs(x = "Month", y = "Count",
       title = "Number of Reported Crimes by Month and Location Description",
       col = "Location Description") +
  scale_color_discrete(name = "",
                       labels = c('Alley', 'Apartment', 'Public parking',
                                  'Residence', 'School, public, building',
                                  'Sidewalk', 'Small retail store', 'Street')) -> ml

#by hour, location
ggplot(data = mydf3) +
  aes(x = Time, y = n, color = ld) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = 0:23) +
  scale_y_continuous(breaks = seq(0, 150000, length.out = 4)) +
  labs(x = "Hour of Day", y = "Count",
       title = "Number of Reported Crimes by Hour and Location Description",
       col = "Location Description") +
  scale_color_discrete(name = "",
                       labels = c('Alley', 'Apartment', 'Public parking',
                                  'Residence', 'School, public, building',
                                  'Sidewalk', 'Small retail store', 'Street')) -> hl

#by type, year
ggplot(data = mydf4) +
  aes(x = Year, y = n, color = pt) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = 2001:2021) +
  scale_y_continuous(breaks = seq(0, 100000, length.out = 5)) +
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5, vjust = 0.5)) +
  labs(x = "Year", y = "Count",
       title = "Number of Reported Crimes by Year and Primary Type",
       col = "Primary Type") +
  scale_color_discrete(name = "") -> yt

#by type, month
mydf5$Month <- as.numeric(mydf5$Month)
ggplot(data = mydf5) +
  aes(x = Month, y = n, color = pt) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = rep(1:12)) +
  scale_y_continuous(breaks = seq(0, 150000, length.out = 4)) +
  labs(x = "Month", y = "Count",
       title = "Number of Reported Crimes by Month and Primary Type",
       col = "Primary Type") +
  scale_color_discrete(name = "") -> mt

#by hour, type
ggplot(data = mydf6) +
  aes(x = Time, y = n, color = pt) +
  geom_point() +
  geom_line() +
  scale_x_continuous(breaks = rep(0:23)) +
  scale_y_continuous(breaks = seq(0, 100000, length.out = 5)) +
  labs(x = "Hour of Day", y = "Count",
       title = "Number of Reported Crimes by Hour and Primary Type",
       col = "Primary Type") +
  scale_color_discrete(name = "") -> ht


```


\pagebreak

```{r, echo=FALSE, fig.height=4, fig.width=9}
yl
ml
hl
```


\pagebreak

```{r, echo=FALSE, fig.height=4, fig.width=9}
yt
mt
ht
```

\pagebreak

```{r, echo=FALSE, fig.align='center', fig.width=10}

types <- c('Deceptive practice', 'Motor vehicle theft',
                                  'Burglary', 'Assault', 'Narcotics',
                                  'Criminal Damage', 'Battery', 'Theft')

circos <- function(type){
  convert_risk <- function(risk, max, min) {
    (risk - min) / (max - min)
  }
  
  mydf6 %>%
    filter(pt == toupper(type)) %>%
    select(Time, n) -> data6
  
  max <- max(data6$n)
  min <- min(data6$n)
  
  data6 %>%
    mutate(relative_risk = convert_risk(n, max, min)) %>%
    select(Time, relative_risk) -> data6
  
  col_fun = colorRamp2(c(0, 0.5, 1), c('white', 'pink', 'red'))
  par(mar = c(2, 2, 2, 2))
  plot(c(-1.2, 1.2), c(-1.2, 1.2), type = "n", axes = FALSE, ann = FALSE, asp = 1)
  angle = 90
  for (i in 0:23) {
    color <- filter(data6, Time == i)$relative_risk
    draw.sector(angle, angle - 15, col = col_fun(color), border = 2)
    angle <-  angle - 15
  }
  title(paste0("Likelihood of ", type)) #data sometimes a best estimate
  text(0, 1.1, '0am')
  text(0, -1.1, '12pm')
  text(1.2, 0, '6am')
  text(-1.2, 0, '6pm')
}


par(mfrow = c(2, 4))
for (i in 1:8){
  circos(types[i])
}
```



