---
title: "Correlation_Plots"
author: "Melody He"
date: '2022-06-17'
output: pdf_document
---

```{r, warning=FALSE, message = FALSE}
library(ggpubr)
library(ggplot2)
library(data.table)
library(dplyr)
library(gridExtra)
library(gt)

df <- fread("C:\\Users\\melod\\Downloads\\crimes.csv")
df <- select(df, -ID, -`Case Number`, -IUCR, -Block, -Description, -`Updated On`, -Ward, -Location)
## secondary dataset
data1 <- fread("C:\\Users\\melod\\Downloads\\poverty.csv")
data1 <- data1[1:77,]
```

```{r, warning = FALSE, message = FALSE}
g1 <- ggplot(data = data1, aes(x = `PERCENT HOUSEHOLDS BELOW POVERTY`)) + 
  geom_histogram(binwidth = 10, color = "plum", fill = "plum1") + xlab("% Households Below Poverty") + ylab("Frequency")
g2 <- ggplot(data = data1, aes(x = `PERCENT AGED 16+ UNEMPLOYED`)) + 
  geom_histogram(binwidth = 10, color = "paleturquoise", fill = "paleturquoise1") + xlab("Percent Unemployed") + ylab("Frequency")
g3 <- ggplot(data = data1, aes(x = `PER CAPITA INCOME`)) + 
  geom_histogram(binwidth = 10000, color = "lightpink", fill = "lightpink1") + xlab("Per Capita Income") + ylab("Frequency")
g4 <- ggplot(data = data1, aes(x = `HARDSHIP INDEX`)) + 
  geom_histogram(binwidth = 20, color = "plum", fill = "plum1") + xlab("Hardship Index (1-100)") + ylab("Frequency")
```


```{r, fig.align='center'}
grid.arrange(g1, g2, g3, g4, nrow = 2)
```


```{r, fig.align = 'center'}
stats <- sapply(data1[,c('PERCENT HOUSEHOLDS BELOW POVERTY', 'PERCENT AGED 16+ UNEMPLOYED', 'PER CAPITA INCOME', 'HARDSHIP INDEX')], summary)
stats <- as.data.frame(round(t(stats), 2))
row.names(stats) <- c("% Households Below Poverty", 
                      "% Aged 16+ Unemployed",
                      "Per Capita Income ($)", 
                      "Hardship Index (1-100)")
stats %>%
  gt(rownames_to_stub = TRUE) %>%
  tab_header(title = "Socioeconomic Indicators Summary (2008-2012)")
```

```{r, warning=FALSE, message = FALSE, include = FALSE}

## obtain subset of Year = 2010
sub <- df[df$Year == 2010,]

## frequency table dataframe
comm <- data.frame(table(sub$`Community Area`)) 
colnames(comm) <- c("Community Area","Crime Rate")
## remove community area 0
comm <-comm[comm$`Community Area` != 0,]
# find crime rate per 10,000 people
comm$`Crime Rate` <- comm$`Crime Rate`/(as.numeric(data1$POPULATION)) * 10000

## merge frequency dataframe with secondary dataset
comm <- merge(comm, data1, by.x = "Community Area", by.y = "Community Area Number")
colors <- c("red", "orange", "green", "blue", "magenta", "purple")

## correlation plots with correlation coefficient and p-values
p1 <- ggplot(data = comm, aes(x = `Crime Rate`, y = `PERCENT HOUSEHOLDS BELOW POVERTY`)) + 
  geom_point(col = colors[1]) + 
  geom_smooth(method='lm', formula= y~x, size = 0.25, col = "black", se = FALSE) + 
  xlab("Crime Rate (per 10000 people)")+ ylab("% Households Below Poverty") +
  stat_cor(label.x = 600, label.y = 55)

p2 <- ggplot(data = comm, aes(x = `Crime Rate`, y = `PERCENT AGED 16+ UNEMPLOYED`)) + 
  geom_point(col = colors[2]) + 
  geom_smooth(method='lm', formula= y~x, size = 0.25, col = "black", se = FALSE) + 
  xlab("Crime Rate (per 10000 people)") + ylab("% unemployed (Ages 16+)") +
  stat_cor(label.x = 600, label.y = 55)

p3 <- ggplot(data = comm, aes(x = `Crime Rate`, y = `PER CAPITA INCOME`, )) + 
  geom_point(col = colors[4]) +geom_smooth(method='lm', formula= y~x, size = 0.25, col = "black", se = FALSE) + 
  xlab("Crime Rate (per 10000 people)") +
  ylab("Per Capita Income") + 
  stat_cor(label.x = 500, label.y = 80000)

p4 <- ggplot(data = comm, aes(x = `Crime Rate`, y = `HARDSHIP INDEX`)) + 
  geom_point( col = colors[5]) + 
  geom_smooth(method='lm', formula= y~x, size = 0.25, col = "black", se = FALSE) + 
  xlab("Crime Rate (per 10000 people)") + ylab("Hardship Index (0-100)") + 
  stat_cor(label.x = 600, label.y = 100)
```


```{r, fig.align = 'center'}
grid.arrange(p1, p2, p3, p4, nrow = 2, top="Four Socioeconomic Factors vs. Crime Rate, 2010")
```

